In [1]:
import sys
import os

# 获取当前工作目录
current_dir = os.getcwd()

# 获取父目录（即 python_dir）
project_dir = os.path.dirname(current_dir)
sys.path.append(project_dir)


import numpy as np
import cupy as cp
import mytorch as torch
import mytorch.ops as ops
import mytorch.nn as nn
import mytorch.optim as optim
import mytorch.data as data
from mytorch.array_device import *
from mytorch.array_api import array_api
import mytorch.perfomance as pf

In [2]:
cp.random.seed(42)
x = torch.Tensor(cp.random.randint(0, 60, size=(1, 64)))
y = nn.TransformerDecoder(vocab_size=60, max_len=64, n_embd=256, n_head=8, n_layer=3, dropout=0.1,device=gpu())
out = y(x)
print(torch.Tensor.total_size)
print(out.shape)
out.backward()

20116480
(1, 64, 60)


In [3]:
x =torch.Tensor(np.random.randint(10, size=(5, 10)))
y = nn.Embedding(1000, 512)
z = y(x)
print(y.weight)
z.backward()
print(y.weight.grad)

[[0.52851    0.2971613  0.89967126 ... 0.66016805 0.65370953 0.40449962]
 [0.530052   0.2852253  0.75224847 ... 0.6720585  0.3244272  0.42505354]
 [0.8350631  0.16035652 0.6536528  ... 0.71736026 0.39393854 0.7565257 ]
 ...
 [0.67624384 0.8432342  0.30938414 ... 0.00423323 0.99009925 0.8387183 ]
 [0.60052264 0.57323235 0.91237104 ... 0.0691051  0.69778997 0.9541951 ]
 [0.13928574 0.44563174 0.6369581  ... 0.67909944 0.4310276  0.76946956]]
[[4. 4. 4. ... 4. 4. 4.]
 [8. 8. 8. ... 8. 8. 8.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
os.getpwd()
with open(project_dir+'/data/Shakespeare/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

FileNotFoundError: [Errno 2] No such file or directory: '/home/meiran/Documents/python/Mytorch/python/data/Shakespeare/input.txt'